WEB:
  port: 6164

LLM:
  Zhipu_glm4_flash:
    llm_params:
      platform: Zhipu
      model_name: glm-4-flash
      api_key: fef479de41cc415d844500ad841478d6.Dab1YJV5IIiz4agQ
      endpoint: https://open.bigmodel.cn/api/paas/v4/


  zhipu_glm4_plus:
    llm_params:
      platform: Zhipu
      model_name: glm-4-plus
      api_key: fef479de41cc415d844500ad841478d6.Dab1YJV5IIiz4agQ
      endpoint: https://open.bigmodel.cn/api/paas/v4/

  Doubao:
    llm_params:
      platform: Doubao
      model_name: doubao-pro-256k
      api_key: b3c547c4-6ecb-416a-8575-7b7498a5b639
      endpoint: https://ark.cn-beijing.volces.com/api/v3/

  DeepSeek:
    llm_params:
      platform: DeepSeek
      model_name: deepseek-chat
      api_key: sk-28b68164d8fc44fba257afaaaafc82b4
      endpoint: https://api.deepseek.com/v1/

