emails:
  default: {
    "server": "smtp.qiye.163.com",
    "user": "CHARTERING@JAH-LINE.COM",
    "password": "BUb4R2u2Z7ac15wN"
  }
cache_path: /Users/anthonyf/Desktop/MetaInFlow/shipment_solution/storage